config/routes.rb
SpecScoreRegistry::Engine.routes.draw do
  devise_for :users, class_name: 'SpecScoreRegistry::User', module: :devise
  get 'dashboard', to: 'dashboards#show'
end

app/models/spec_score_registry/user.rb
module SpecScoreRegistry
  class User < ActiveRecord::Base
    self.table_name = 'sc_users'

    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :trackable, :validatable
  end
end

app/controllers/spec_score_registry/application_controller.rb
module SpecScoreRegistry
  class ApplicationController < ::ApplicationController
  end
end

app/controllers/spec_score_registry/dashboards_controller.rb
require_dependency "spec_score_registry/application_controller"

module SpecScoreRegistry
  class DashboardsController < ApplicationController
    before_action :authenticate_user!

    # GET /dashboards
    def index
    end

    def show
      @user = current_user
    end

    private

      # Only allow a trusted parameter "white list" through.
      def dashboard_params
        params.require(:dashboard).permit(:index)
      end
  end
end

app/helpers/spec_score_registry/application_helper.rb
module SpecScoreRegistry
  module ApplicationHelper
  end
end

app/helpers/spec_score_registry/dashboards_helper.rb
module SpecScoreRegistry
  module DashboardsHelper
  end
end

app/views/spec_score_registry/dashboards/_form.html.erb
<%= form_for(@dashboard) do |f| %>
  <% if @dashboard.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dashboard.errors.count, "error") %> prohibited this dashboard from being saved:</h2>

      <ul>
      <% @dashboard.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :index %><br>
    <%= f.text_field :index %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/spec_score_registry/dashboards/edit.html.erb
<h1>Editing dashboard</h1>

<%= render 'form' %>

<%= link_to 'Show', @dashboard %> |
<%= link_to 'Back', dashboards_path %>

app/views/spec_score_registry/dashboards/index.html.erb
<h1>Listing dashboards</h1>

<table>
  <thead>
    <tr>
      <th>Index</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dashboards.each do |dashboard| %>
      <tr>
        <td><%= dashboard.index %></td>
        <td><%= link_to 'Show', dashboard %></td>
        <td><%= link_to 'Edit', edit_dashboard_path(dashboard) %></td>
        <td><%= link_to 'Destroy', dashboard, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dashboard', new_dashboard_path %>

app/views/spec_score_registry/dashboards/new.html.erb
<h1>New dashboard</h1>

<%= render 'form' %>

<%= link_to 'Back', dashboards_path %>

app/views/spec_score_registry/dashboards/show.html.erb
<p id="notice"><%= notice %></p>
<div class='well'>
  <h2>welcome on your dashboard</h2>
</div>